// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0YDp269-HRZzHVL08OnkD1VYvLcgQKs',
    appId: '1:305348355094:web:da5b52066d7a78d4f38137',
    messagingSenderId: '305348355094',
    projectId: 'fleet-management-system-cb0ce',
    authDomain: 'fleet-management-system-cb0ce.firebaseapp.com',
    storageBucket: 'fleet-management-system-cb0ce.appspot.com',
    measurementId: 'G-E7M5XY7WXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz4tWRu-GdlVHd4Ocu7rxRsqaaq0V8oHk',
    appId: '1:305348355094:android:a9f44b42b750dfe1f38137',
    messagingSenderId: '305348355094',
    projectId: 'fleet-management-system-cb0ce',
    storageBucket: 'fleet-management-system-cb0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxSVjv1yCpl-1iSIhH6RbkAviz2T6xs8E',
    appId: '1:305348355094:ios:fff1ef33872f2e2cf38137',
    messagingSenderId: '305348355094',
    projectId: 'fleet-management-system-cb0ce',
    storageBucket: 'fleet-management-system-cb0ce.appspot.com',
    iosClientId: '305348355094-p94htmp74bg9438fh6pf8sqfjigbobjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxSVjv1yCpl-1iSIhH6RbkAviz2T6xs8E',
    appId: '1:305348355094:ios:4d0ce6e83da8296df38137',
    messagingSenderId: '305348355094',
    projectId: 'fleet-management-system-cb0ce',
    storageBucket: 'fleet-management-system-cb0ce.appspot.com',
    iosClientId: '305348355094-u6agototoifjh2bj2bgmkm5k5p06obkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo.RunnerTests',
  );
}
